name: Python Build, Run & Test API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. 设置 Python 环境
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. 安装项目依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pytest requests  # 安装 pyinstaller 和 requests 库

    # # 4. 运行测试 (确保接口可以运行)
    # - name: Run tests before building exe
    #   run: |
    #     pytest --maxfail=1 --disable-warnings -q

    # 5. 使用 PyInstaller 打包 .exe 文件
    - name: Build .exe with PyInstaller
      run: |
        pyinstaller --onefile main.py  # 假设你的主脚本是 main.py

    # 6. 列出文件结构，确认 .exe 是否生成
    - name: List files after PyInstaller build
      run: |
        Get-ChildItem -Path "D:/a/py_prj_pub_test/py_prj_pub_test/dist" -Recurse | Select-Object FullName


    - name: Run the exe file in the background
      run: |
        Start-Process "D:/a/py_prj_pub_test/py_prj_pub_test/dist/main.exe" & python -c "import requests; response = requests.get('http://127.0.0.1:8080/api/health'); assert response.status_code == 200, f'API failed with status code {response.status_code}'"


    # 7. 等待几秒钟确保 .exe 启动完成
    - name: Wait for 5 seconds
      run: |
        Start-Sleep -Seconds 5
